services:
  - type: web
    name: bloodmap-api
    env: docker
    rootDir: bloodmap_api
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: bloodmap-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: bloodmap-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: bloodmap-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: bloodmap-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: bloodmap-db
          property: password

databases:
  - name: bloodmap-db
    databaseName: blood_ph
    user: blood_ph
    plan: free
